^CTraceback (most recent call last):
  File "/home/ndaimm/ndaimm/onhost/main.py", line 197, in <module>
    main()
  File "/home/ndaimm/ndaimm/onhost/main.py", line 191, in main
    t.join()  # Ensure all threads have finished before exiting
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
^CKeyboardInterrupt: 


